### ISSUE TITLE
formatHelp颜色问题

### ISSUE THREAD

**Issue by AdvancedMical** [Polar-Pumpkin/ParrotX#2]
src/main/java/org/serverct/parrot/parrotx/command/CommandHandler.java 106行
 没使用颜色代码替换(I18n.color)导致颜色代码无效

**Comment by Polar-Pumpkin** [comment]
懂了，马上修，谢谢大佬。
居然还会有人给 ParrotX 发 Issue。
其实是知道这个问题的，但是更新 ParrotX 太麻烦了，所以通常只在需要大改动的情况下才更新 ParrotX，比如要添加新的方法。

**Comment by Polar-Pumpkin** [comment]
已修复，同时更新已编辑到VoteUp(Shoal)项目 v2.0.4-VU 更新中。ParrotX 版本号未发生改变，仍未 v1.0.31-alpha。

**Comment by AdvancedMical** [comment]
有点好用所以在关注（
